from django.urls import path

from applications.api.views import (
    CategoryListAPIView,
    ChangePasswordAPIView,
    ConversationDetailAPIView,
    ConversationListCreateAPIView,
    FavoriteListAPIView,
    FavoriteToggleAPIView,
    HomeAPIView,
    ListingDetailAPIView,
    ListingListCreateAPIView,
    ListingOfferAPIView,
    ListingSearchAPIView,
    LoginAPIView,
    GoogleLoginAPIView,
    LogoutAPIView,
    MeAPIView,
    MeListingsAPIView,
    MessageCreateAPIView,
    MessageReadAPIView,
    MessageViewOnceAPIView,
    NotificationListAPIView,
    NotificationMarkReadAPIView,
    NotificationReadAllAPIView,
    NotificationUnreadCountAPIView,
    PayPalCancelSubscriptionAPIView,
    PayPalConfirmSubscriptionAPIView,
    PayPalCreateSubscriptionAPIView,
    StripeCancelSubscriptionAPIView,
    StripeConfirmSessionAPIView,
    StripeCreateCheckoutSessionAPIView,
    ProfileDetailAPIView,
    ProfileReviewAPIView,
    RefreshAPIView,
    RegisterAPIView,
    StoryDetailAPIView,
    StoryListCreateAPIView,
    ListingReportAPIView,
    BugReportCreateAPIView,
)


urlpatterns = [
    path("categories/", CategoryListAPIView.as_view(), name="api-categories"),
    path("listings/", ListingListCreateAPIView.as_view(), name="api-listings"),
    path("listings/<int:pk>/", ListingDetailAPIView.as_view(), name="api-listing-detail"),
    path("listings/<int:pk>/favorite/", FavoriteToggleAPIView.as_view(), name="api-listing-favorite"),
    path("listings/<int:pk>/offer/", ListingOfferAPIView.as_view(), name="api-listing-offer"),
    path("listings/<int:pk>/report/", ListingReportAPIView.as_view(), name="api-listing-report"),
    path("search/", ListingSearchAPIView.as_view(), name="api-search"),
    path("home/", HomeAPIView.as_view(), name="api-home"),
    path("me/", MeAPIView.as_view(), name="api-me"),
    path("me/listings/", MeListingsAPIView.as_view(), name="api-me-listings"),
    path("me/favorites/", FavoriteListAPIView.as_view(), name="api-me-favorites"),
    path("paypal/create-subscription/", PayPalCreateSubscriptionAPIView.as_view(), name="api-paypal-create-subscription"),
    path("paypal/confirm-subscription/", PayPalConfirmSubscriptionAPIView.as_view(), name="api-paypal-confirm-subscription"),
    path("paypal/cancel-subscription/", PayPalCancelSubscriptionAPIView.as_view(), name="api-paypal-cancel-subscription"),
    path("stripe/create-session/", StripeCreateCheckoutSessionAPIView.as_view(), name="api-stripe-create-session"),
    path("stripe/confirm-session/", StripeConfirmSessionAPIView.as_view(), name="api-stripe-confirm-session"),
    path("stripe/cancel-subscription/", StripeCancelSubscriptionAPIView.as_view(), name="api-stripe-cancel-subscription"),
    path("profiles/<str:username>/", ProfileDetailAPIView.as_view(), name="api-profile-detail"),
    path("profiles/<str:username>/reviews/", ProfileReviewAPIView.as_view(), name="api-profile-review"),
    path("conversations/", ConversationListCreateAPIView.as_view(), name="api-conversations"),
    path("conversations/<int:pk>/", ConversationDetailAPIView.as_view(), name="api-conversation-detail"),
    path("messages/", MessageCreateAPIView.as_view(), name="api-message-create"),
    path("messages/<int:pk>/read/", MessageReadAPIView.as_view(), name="api-message-read"),
    path("messages/<int:pk>/view-once/", MessageViewOnceAPIView.as_view(), name="api-message-view-once"),
    path("stories/", StoryListCreateAPIView.as_view(), name="api-stories"),
    path("stories/<int:pk>/", StoryDetailAPIView.as_view(), name="api-story-detail"),
    path("auth/register/", RegisterAPIView.as_view(), name="api-register"),
    path("auth/login/", LoginAPIView.as_view(), name="api-login"),
    path("auth/google/", GoogleLoginAPIView.as_view(), name="api-google-login"),
    path("auth/password/change/", ChangePasswordAPIView.as_view(), name="api-change-password"),
    path("auth/refresh/", RefreshAPIView.as_view(), name="api-refresh"),
    path("auth/logout/", LogoutAPIView.as_view(), name="api-logout"),
    path("notifications/", NotificationListAPIView.as_view(), name="api-notifications"),
    path("notifications/unread-count/", NotificationUnreadCountAPIView.as_view(), name="api-notifications-unread-count"),
    path("notifications/<int:pk>/read/", NotificationMarkReadAPIView.as_view(), name="api-notifications-read"),
    path("notifications/read-all/", NotificationReadAllAPIView.as_view(), name="api-notifications-read-all"),
    path("report-bug/", BugReportCreateAPIView.as_view(), name="api-report-bug"),
]
