DEPARTMENTS = [
    {
        "slug": "boaco",
        "name": "Boaco",
        "cities": [
            "Boaco",
            "Camoapa",
            "San José de los Remates",
            "San Lorenzo",
            "Santa Lucía",
            "Teustepe",
        ],
    },
    {
        "slug": "carazo",
        "name": "Carazo",
        "cities": [
            "Diriamba",
            "Dolores",
            "El Rosario",
            "Jinotepe",
            "La Conquista",
            "La Paz de Carazo",
            "San Marcos",
            "Santa Teresa",
        ],
    },
    {
        "slug": "chinandega",
        "name": "Chinandega",
        "cities": [
            "Chichigalpa",
            "Chinandega",
            "Cinco Pinos",
            "Corinto",
            "El Realejo",
            "El Viejo",
            "Posoltega",
            "Puerto Morazán",
            "San Francisco del Norte",
            "San Pedro del Norte",
            "Santo Tomás del Norte",
            "Somotillo",
            "Villanueva",
        ],
    },
    {
        "slug": "chontales",
        "name": "Chontales",
        "cities": [
            "Acoyapa",
            "Comalapa",
            "El Ayote",
            "El Coral",
            "Juigalpa",
            "La Libertad",
            "San Francisco de Cuapa",
            "San Pedro de Lóvago",
            "Santo Domingo",
            "Santo Tomás",
        ],
    },
    {
        "slug": "esteli",
        "name": "Estelí",
        "cities": [
            "Condega",
            "Estelí",
            "La Trinidad",
            "Pueblo Nuevo",
            "San Juan de Limay",
            "San Nicolás",
        ],
    },
    {
        "slug": "granada",
        "name": "Granada",
        "cities": [
            "Diriá",
            "Diriomo",
            "Granada",
            "Nandaime",
        ],
    },
    {
        "slug": "jinotega",
        "name": "Jinotega",
        "cities": [
            "El Cuá",
            "Jinotega",
            "La Concordia",
            "San José de Bocay",
            "San Rafael del Norte",
            "San Sebastián de Yalí",
            "Santa María de Pantasma",
            "Wiwilí de Jinotega",
        ],
    },
    {
        "slug": "leon",
        "name": "León",
        "cities": [
            "Achuapa",
            "El Jicaral",
            "El Sauce",
            "La Paz Centro",
            "Larreynaga",
            "León",
            "Nagarote",
            "Quezalguaque",
            "Santa Rosa del Peñón",
            "Telica",
        ],
    },
    {
        "slug": "madriz",
        "name": "Madriz",
        "cities": [
            "Las Sabanas",
            "Palacagüina",
            "San José de Cusmapa",
            "San Juan de Río Coco",
            "San Lucas",
            "Somoto",
            "Telpaneca",
            "Totogalpa",
            "Yalagüina",
        ],
    },
    {
        "slug": "managua",
        "name": "Managua",
        "cities": [
            "Ciudad Sandino",
            "El Crucero",
            "Managua",
            "Mateare",
            "San Francisco Libre",
            "San Rafael del Sur",
            "Ticuantepe",
            "Tipitapa",
            "Villa Carlos Fonseca",
        ],
    },
    {
        "slug": "masaya",
        "name": "Masaya",
        "cities": [
            "Catarina",
            "La Concepción",
            "Masatepe",
            "Masaya",
            "Nandasmo",
            "Nindirí",
            "Niquinohomo",
            "San Juan de Oriente",
            "Tisma",
        ],
    },
    {
        "slug": "matagalpa",
        "name": "Matagalpa",
        "cities": [
            "Ciudad Darío",
            "Esquipulas",
            "Matagalpa",
            "Matiguás",
            "Muy Muy",
            "Rancho Grande",
            "Río Blanco",
            "San Dionisio",
            "San Isidro",
            "San Ramón",
            "Sébaco",
            "Terrabona",
            "Tuma-La Dalia",
        ],
    },
    {
        "slug": "nueva-segovia",
        "name": "Nueva Segovia",
        "cities": [
            "Ciudad Antigua",
            "Dipilto",
            "El Jícaro",
            "Jalapa",
            "Macuelizo",
            "Mozonte",
            "Murra",
            "Ocotal",
            "Quilalí",
            "San Fernando",
            "Santa María",
            "Wiwilí de Nueva Segovia",
        ],
    },
    {
        "slug": "rivas",
        "name": "Rivas",
        "cities": [
            "Altagracia",
            "Belén",
            "Buenos Aires",
            "Cárdenas",
            "Moyogalpa",
            "Potosí",
            "Rivas",
            "San Jorge",
            "San Juan del Sur",
            "Tola",
        ],
    },
    {
        "slug": "rio-san-juan",
        "name": "Río San Juan",
        "cities": [
            "El Almendro",
            "El Castillo",
            "Morrito",
            "San Carlos",
            "San Juan del Norte",
            "San Miguelito",
        ],
    },
    {
        "slug": "raccn",
        "name": "Costa Caribe Norte",
        "cities": [
            "Bonanza",
            "Mulukukú",
            "Prinzapolka",
            "Puerto Cabezas",
            "Rosita",
            "Siuna",
            "Waslala",
            "Waspán",
        ],
    },
    {
        "slug": "raccs",
        "name": "Costa Caribe Sur",
        "cities": [
            "Bluefields",
            "Bocana de Paiwas",
            "Corn Island",
            "Desembocadura de la Cruz de Río Grande",
            "El Rama",
            "El Tortuguero",
            "Kukra Hill",
            "La Cruz de Río Grande",
            "Laguna de Perlas",
            "Muelle de los Bueyes",
            "Nueva Guinea",
            "Paiwas",
        ],
    },
]