# Generated by Django 6.0.4 on 2026-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
