# Generated by Django 6.0.4 on 2026-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Palabras clave para el buscador (ej: celular, movil, cable)'),
        ),
    ]
