# Generated by Django 6.0.4 on 2026-04-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_start',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
    ]
