# Generated by Django 6.0.4 on 2026-04-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_story_audio_name_story_audio_start_story_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='payment_methods',
            field=models.CharField(default='Efectivo', max_length=200),
        ),
    ]
