# Generated by Django 6.0.4 on 2026-04-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
