# Generated by Django 6.0.4 on 2026-04-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profilereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
