# Generated by Django 6.0.4 on 2026-04-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_subcategory_and_listing_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
    ]
