# Generated by Django 6.0.4 on 2026-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Palabras clave para el buscador (ej: celular, movil, cable)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Palabras clave para el buscador'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la categoría'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de la subcategoría'),
        ),
    ]
