# Generated by Django 6.0.4 on 2026-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_category_keywords_subcategory_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número primero)'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
    ]
