# Generated by Django 6.0.4 on 2026-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_category_order_alter_subcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Está el anuncio visible al público?'),
        ),
    ]
