# Generated by Django 6.0.4 on 2026-04-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_listing_slug'),
        ('core', '0027_listing_is_active'),
    ]

    operations = [
    ]
