# Generated by Django 6.0.4 on 2026-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
