# Generated by Django 6.0.4 on 2026-04-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_message_is_view_once_message_is_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_viewed',
            new_name='viewed_by_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='viewed_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
