# Generated by Django 6.0.4 on 2026-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_reset_legacy_featured_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
