# Generated by Django 6.0.4 on 2026-04-26 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_bugreport_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bugreport',
            options={'verbose_name': 'Reporte de fallo', 'verbose_name_plural': 'Reportes de fallo'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Anuncio', 'verbose_name_plural': 'Anuncios'},
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'verbose_name': 'Imagen de anuncio', 'verbose_name_plural': 'Imágenes de anuncio'},
        ),
        migrations.AlterModelOptions(
            name='marketingconsent',
            options={'verbose_name': 'Consentimiento de marketing', 'verbose_name_plural': 'Consentimientos de marketing'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='profilereview',
            options={'verbose_name': 'Valoración de perfil', 'verbose_name_plural': 'Valoraciones de perfil'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Historial de búsqueda', 'verbose_name_plural': 'Historiales de búsqueda'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historia', 'verbose_name_plural': 'Historias'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Orden de visualización (menor número primero)', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Está el anuncio visible al público?', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_featured_paid',
            field=models.BooleanField(default=False, help_text='¿Anuncio destacado/priorizado?', verbose_name='destacado'),
        ),
        migrations.AlterField(
            model_name='marketingconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='¿Es usuario Pro?', verbose_name='pro'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verificado'),
        ),
        migrations.AlterField(
            model_name='profilereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado el'),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado el'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Orden de visualización', verbose_name='orden'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Nuevo mensaje'), ('offer', 'Nueva oferta'), ('favorite', 'Anuncio guardado'), ('system', 'Sistema')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conversation')),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
