# Generated by Django 6.0.4 on 2026-04-26 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_bugreport_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', 'Fraude o estafa'), ('spam', 'Spam / Anuncio repetido'), ('inappropriate', 'Contenido inapropiado / Ofensivo'), ('wrong_category', 'Categoría incorrecta'), ('sold', 'Ya se vendió'), ('other', 'Otro motivo')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de anuncio',
                'verbose_name_plural': 'Reportes de anuncio',
            },
        ),
    ]
