# Generated by Django 6.0.5 on 2026-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_duplicate_deporte_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_negotiable',
            field=models.BooleanField(default=False, help_text="Si está marcado, se muestra 'Negociable' en vez de un precio fijo.", verbose_name='precio negociable'),
        ),
    ]
