# Generated by Django 6.0.4 on 2026-08-16 13:27

from django.db import migrations

def add_books_category(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Subcategory = apps.get_model('core', 'Subcategory')

    # Create Category
    books_category, _ = Category.objects.update_or_create(
        slug='libros',
        defaults={
            'name': 'Libros',
            'icon': '📚',
            'description': 'Libros de texto, novelas, enciclopedias, historia, filosofía y más.',
            'keywords': 'libros, lectura, literatura, novelas, historia, filosofia, enciclopedias, texto',
            'order': 100,
        }
    )

    # Create Subcategories
    subcategories = [
        {'name': 'Historia', 'slug': 'libros-historia', 'icon': '🏛️', 'description': 'Libros sobre historia universal y local.', 'order': 10},
        {'name': 'Filosofía', 'slug': 'libros-filosofia', 'icon': '🤔', 'description': 'Obras filosóficas y de pensamiento crítico.', 'order': 20},
        {'name': 'Ficción y Literatura', 'slug': 'libros-ficcion', 'icon': '📖', 'description': 'Novelas, cuentos y poesía.', 'order': 30},
        {'name': 'Ciencia y Tecnología', 'slug': 'libros-ciencia', 'icon': '🔬', 'description': 'Libros científicos, de divulgación y tecnología.', 'order': 40},
        {'name': 'Arte y Diseño', 'slug': 'libros-arte', 'icon': '🎨', 'description': 'Libros sobre artes visuales, diseño y música.', 'order': 50},
        {'name': 'Infantiles y Juveniles', 'slug': 'libros-infantiles', 'icon': '🧒', 'description': 'Libros para niños y jóvenes.', 'order': 60},
        {'name': 'Educación y Texto', 'slug': 'libros-educacion', 'icon': '📓', 'description': 'Libros escolares y universitarios.', 'order': 70},
        {'name': 'Otros Libros', 'slug': 'libros-otros', 'icon': '📚', 'description': 'Cómics, revistas y otros tipos de lectura.', 'order': 80},
    ]

    for sub in subcategories:
        Subcategory.objects.update_or_create(
            slug=sub['slug'],
            defaults={
                'category': books_category,
                'name': sub['name'],
                'icon': sub['icon'],
                'description': sub['description'],
                'keywords': sub['name'].lower() + ', libros',
                'order': sub['order'],
            }
        )

def remove_books_category(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Category.objects.filter(slug='libros').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_listing_updated_at'),
    ]

    operations = [
        migrations.RunPython(add_books_category, remove_books_category),
    ]
