# Generated by Django 6.0.5 on 2026-08-16 13:33

from django.db import migrations

def expand_subcategories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Subcategory = apps.get_model('core', 'Subcategory')

    subcategories_data = {
        'nino': [
            {'name': 'Pantalones y Shorts', 'slug': 'nino-pantalones-shorts', 'icon': '👖', 'description': 'Pantalones, shorts y jeans para niños.', 'order': 10},
            {'name': 'Camisas y Polos', 'slug': 'nino-camisas', 'icon': '👕', 'description': 'Camisas, camisetas y polos para niños.', 'order': 20},
            {'name': 'Zapatos y Tenis', 'slug': 'nino-zapatos', 'icon': '👟', 'description': 'Zapatos, tenis y sandalias para niños.', 'order': 30},
            {'name': 'Ropa Interior y Pijamas', 'slug': 'nino-ropa-interior', 'icon': '🧦', 'description': 'Ropa interior, calcetines y pijamas.', 'order': 40},
            {'name': 'Juguetes y Juegos', 'slug': 'nino-juguetes', 'icon': '🏎️', 'description': 'Carritos, figuras de acción y juegos.', 'order': 50},
            {'name': 'Uniformes Escolares', 'slug': 'nino-uniformes', 'icon': '🎒', 'description': 'Uniformes para colegio y escuela.', 'order': 60},
            {'name': 'Accesorios', 'slug': 'nino-accesorios', 'icon': '🧢', 'description': 'Gorras, cinturones y otros accesorios.', 'order': 70},
        ],
        'nina': [
            {'name': 'Vestidos y Faldas', 'slug': 'nina-vestidos', 'icon': '👗', 'description': 'Vestidos, faldas y conjuntos para niñas.', 'order': 10},
            {'name': 'Blusas y Camisetas', 'slug': 'nina-blusas', 'icon': '👚', 'description': 'Blusas, tops y camisetas para niñas.', 'order': 20},
            {'name': 'Zapatos y Sandalias', 'slug': 'nina-zapatos', 'icon': '🥿', 'description': 'Zapatos, sandalias y tenis para niñas.', 'order': 30},
            {'name': 'Prensapelos y Lazos', 'slug': 'nina-prensapelos', 'icon': '🎀', 'description': 'Lazos, diademas y prensapelos.', 'order': 40},
            {'name': 'Accesorios y Joyería', 'slug': 'nina-accesorios', 'icon': '💍', 'description': 'Aretes, pulseras y collares infantiles.', 'order': 50},
            {'name': 'Juguetes y Muñecas', 'slug': 'nina-juguetes', 'icon': '🧸', 'description': 'Muñecas, peluches y juegos.', 'order': 60},
            {'name': 'Ropa Interior y Pijamas', 'slug': 'nina-ropa-interior', 'icon': '🧦', 'description': 'Ropa interior y pijamas para niñas.', 'order': 70},
            {'name': 'Uniformes Escolares', 'slug': 'nina-uniformes', 'icon': '🎒', 'description': 'Uniformes para colegio y escuela.', 'order': 80},
        ],
        'jardineria': [
            {'name': 'Abonos y Fertilizantes', 'slug': 'jardineria-abonos', 'icon': '🌱', 'description': 'Abonos, tierra y fertilizantes.', 'order': 40},
            {'name': 'Muebles de Exterior', 'slug': 'jardineria-muebles', 'icon': '🪑', 'description': 'Muebles para patio y jardín.', 'order': 50},
            {'name': 'Riego y Mangueras', 'slug': 'jardineria-riego', 'icon': '💧', 'description': 'Sistemas de riego, mangueras y aspersores.', 'order': 60},
            {'name': 'Paisajismo y Diseño', 'slug': 'jardineria-paisajismo', 'icon': '🏞️', 'description': 'Elementos de paisajismo y decoración exterior.', 'order': 70},
        ],
        'moda': [
            {'name': 'Maquillaje y Cosméticos', 'slug': 'moda-maquillaje', 'icon': '💄', 'description': 'Maquillaje y productos cosméticos.', 'order': 60},
            {'name': 'Cuidado de la Piel', 'slug': 'moda-cuidado-piel', 'icon': '🧴', 'description': 'Cremas, serums y cuidado facial/corporal.', 'order': 70},
            {'name': 'Sombreros y Gorras', 'slug': 'moda-sombreros', 'icon': '🧢', 'description': 'Sombreros, gorras y viseras.', 'order': 80},
            {'name': 'Calzado de Diseño', 'slug': 'moda-calzado', 'icon': '👠', 'description': 'Zapatos y calzado de moda.', 'order': 90},
        ]
    }

    for cat_slug, subs in subcategories_data.items():
        try:
            category = Category.objects.get(slug=cat_slug)
            for sub in subs:
                Subcategory.objects.update_or_create(
                    slug=sub['slug'],
                    defaults={
                        'category': category,
                        'name': sub['name'],
                        'icon': sub['icon'],
                        'description': sub['description'],
                        'keywords': sub['name'].lower(),
                        'order': sub['order'],
                    }
                )
        except Category.DoesNotExist:
            continue

def remove_subcategories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_books_category'),
    ]

    operations = [
        migrations.RunPython(expand_subcategories, remove_subcategories),
    ]
