# Generated by Django 6.0.5 on 2026-08-16 13:35

from django.db import migrations

def expand_mascotas_accessories(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Subcategory = apps.get_model('core', 'Subcategory')

    subcategories_data = {
        'mascotas': [
            {'name': 'Accesorios para Perros', 'slug': 'mascotas-accesorios-perros', 'icon': '🦮', 'description': 'Collares, correas, camas y accesorios para perros.', 'order': 70},
            {'name': 'Accesorios para Gatos', 'slug': 'mascotas-accesorios-gatos', 'icon': '🧶', 'description': 'Areneros, rascadores y accesorios para gatos.', 'order': 80},
            {'name': 'Acuarios y Accesorios', 'slug': 'mascotas-acuarios-accesorios', 'icon': '🐠', 'description': 'Peceras, filtros, bombas y decoración.', 'order': 90},
            {'name': 'Jaulas y Accesorios (Aves/Roedores)', 'slug': 'mascotas-jaulas-accesorios', 'icon': '🦜', 'description': 'Jaulas, bebederos y juguetes para aves y roedores.', 'order': 100},
            {'name': 'Ropa para Mascotas', 'slug': 'mascotas-ropa', 'icon': '🧥', 'description': 'Abrigos, suéteres y zapatos para mascotas.', 'order': 110},
            {'name': 'Juguetes para Mascotas', 'slug': 'mascotas-juguetes', 'icon': '🎾', 'description': 'Pelotas, mordederas y juguetes interactivos.', 'order': 120},
            {'name': 'Camas y Transportadoras', 'slug': 'mascotas-camas-transportadoras', 'icon': '🧳', 'description': 'Casas, camas y jaulas transportadoras.', 'order': 130},
            {'name': 'Salud e Higiene', 'slug': 'mascotas-salud-higiene', 'icon': '🧼', 'description': 'Champú, cepillos, antipulgas y vitaminas.', 'order': 140},
        ]
    }

    for cat_slug, subs in subcategories_data.items():
        try:
            category = Category.objects.get(slug=cat_slug)
            for sub in subs:
                Subcategory.objects.update_or_create(
                    slug=sub['slug'],
                    defaults={
                        'category': category,
                        'name': sub['name'],
                        'icon': sub['icon'],
                        'description': sub['description'],
                        'keywords': sub['name'].lower() + ', accesorios',
                        'order': sub['order'],
                    }
                )
        except Category.DoesNotExist:
            continue

def remove_mascotas_accessories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_expand_subcategories'),
    ]

    operations = [
        migrations.RunPython(expand_mascotas_accessories, remove_mascotas_accessories),
    ]
