# Generated by Django 6.0.5 on 2026-08-16 13:37

from django.db import migrations

def expand_mascotas_accessories_more(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Subcategory = apps.get_model('core', 'Subcategory')

    subcategories_data = {
        'mascotas': [
            {'name': 'Alimento y Snacks', 'slug': 'mascotas-alimento-snacks', 'icon': '🦴', 'description': 'Comida, croquetas y premios para mascotas.', 'order': 150},
            {'name': 'Comederos y Bebederos', 'slug': 'mascotas-comederos-bebederos', 'icon': '🥣', 'description': 'Platos, fuentes de agua y dispensadores.', 'order': 160},
            {'name': 'Collares, Correas y Arneses', 'slug': 'mascotas-collares-correas', 'icon': '🪢', 'description': 'Accesorios de paseo y seguridad.', 'order': 170},
            {'name': 'Areneros y Sustratos', 'slug': 'mascotas-areneros', 'icon': '🚽', 'description': 'Cajas de arena, arena para gatos y sustratos.', 'order': 180},
            {'name': 'Rascadores y Árboles', 'slug': 'mascotas-rascadores', 'icon': '🌳', 'description': 'Gimnasios y rascadores para gatos.', 'order': 190},
            {'name': 'Identificaciones y Chips', 'slug': 'mascotas-identificaciones', 'icon': '🏷️', 'description': 'Placas, collares GPS y microchips.', 'order': 200},
            {'name': 'Entrenamiento y Adiestramiento', 'slug': 'mascotas-entrenamiento', 'icon': '🏅', 'description': 'Clickers, collares de adiestramiento y repelentes.', 'order': 210},
            {'name': 'Peluquería y Estética', 'slug': 'mascotas-peluqueria', 'icon': '✂️', 'description': 'Máquinas de cortar pelo, tijeras y perfumes.', 'order': 220},
            {'name': 'Ropa y Accesorios Decorativos', 'slug': 'mascotas-ropa-decorativa', 'icon': '🎀', 'description': 'Disfraces, moños, bandanas y gafas.', 'order': 230},
            {'name': 'Accesorios para Reptiles', 'slug': 'mascotas-accesorios-reptiles', 'icon': '🦎', 'description': 'Terrarios, focos térmicos y sustrato para reptiles.', 'order': 240},
        ]
    }

    for cat_slug, subs in subcategories_data.items():
        try:
            category = Category.objects.get(slug=cat_slug)
            for sub in subs:
                Subcategory.objects.update_or_create(
                    slug=sub['slug'],
                    defaults={
                        'category': category,
                        'name': sub['name'],
                        'icon': sub['icon'],
                        'description': sub['description'],
                        'keywords': sub['name'].lower() + ', accesorios',
                        'order': sub['order'],
                    }
                )
        except Category.DoesNotExist:
            continue

def remove_mascotas_accessories_more(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_mascotas_accessories'),
    ]

    operations = [
        migrations.RunPython(expand_mascotas_accessories_more, remove_mascotas_accessories_more),
    ]
