# Generated by Django 6.0.5 on 2026-08-16 13:39

from django.db import migrations

def expand_tech_gaming(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    Subcategory = apps.get_model('core', 'Subcategory')

    subcategories_data = {
        'tecnologia': [
            {'name': 'Auriculares y Cascos', 'slug': 'tech-auriculares-cascos', 'icon': '🎧', 'description': 'Auriculares inalámbricos, de diadema y audífonos.', 'order': 100},
            {'name': 'Smartwatches y Wearables', 'slug': 'tech-smartwatches', 'icon': '⌚', 'description': 'Relojes inteligentes y pulseras de actividad.', 'order': 110},
            {'name': 'Monitores y Pantallas', 'slug': 'tech-monitores', 'icon': '🖥️', 'description': 'Monitores para PC y gaming.', 'order': 120},
            {'name': 'Almacenamiento (USB, Discos)', 'slug': 'tech-almacenamiento', 'icon': '💾', 'description': 'Discos duros, SSD y memorias USB.', 'order': 130},
            {'name': 'Impresoras y Escáneres', 'slug': 'tech-impresoras', 'icon': '🖨️', 'description': 'Impresoras, cartuchos y equipos de oficina.', 'order': 140},
            {'name': 'Redes y Routers', 'slug': 'tech-redes', 'icon': '📡', 'description': 'Routers, repetidores y antenas WiFi.', 'order': 150},
            {'name': 'Componentes de PC', 'slug': 'tech-componentes', 'icon': '⚙️', 'description': 'Tarjetas gráficas, memoria RAM, procesadores.', 'order': 160},
            {'name': 'Proyectores', 'slug': 'tech-proyectores', 'icon': '📽️', 'description': 'Proyectores de cine en casa y oficina.', 'order': 170},
            {'name': 'Drones y Robótica', 'slug': 'tech-drones', 'icon': '🛸', 'description': 'Drones, partes y robots.', 'order': 180},
        ],
        'electro': [
            {'name': 'Refrigeradoras y Congeladores', 'slug': 'electro-refrigeradoras', 'icon': '🧊', 'description': 'Refrigeradoras, neveras y freezers.', 'order': 50},
            {'name': 'Lavadoras y Secadoras', 'slug': 'electro-lavadoras', 'icon': '🧺', 'description': 'Lavadoras, centros de lavado y secadoras.', 'order': 60},
            {'name': 'Cocinas y Hornos', 'slug': 'electro-cocinas', 'icon': '🍳', 'description': 'Cocinas de gas, eléctricas y hornos.', 'order': 70},
            {'name': 'Microondas', 'slug': 'electro-microondas', 'icon': '🥘', 'description': 'Hornos microondas.', 'order': 80},
            {'name': 'Licuadoras y Batidoras', 'slug': 'electro-licuadoras', 'icon': '🍹', 'description': 'Extractores, licuadoras y batidoras.', 'order': 90},
            {'name': 'Cafeteras', 'slug': 'electro-cafeteras', 'icon': '☕', 'description': 'Cafeteras y percoladoras.', 'order': 100},
            {'name': 'Planchas y Cuidado Ropa', 'slug': 'electro-planchas', 'icon': '👔', 'description': 'Planchas de ropa y vaporizadores.', 'order': 110},
            {'name': 'Aspiradoras y Limpieza', 'slug': 'electro-aspiradoras', 'icon': '🧹', 'description': 'Aspiradoras y limpiadores eléctricos.', 'order': 120},
            {'name': 'Aires Acondicionados', 'slug': 'electro-aires', 'icon': '❄️', 'description': 'Splits, aires de ventana y portátiles.', 'order': 130},
            {'name': 'Ventiladores', 'slug': 'electro-ventiladores', 'icon': '🌀', 'description': 'Ventiladores de techo y pedestal.', 'order': 140},
        ],
        'videojuegos': [
            {'name': 'Juegos para PlayStation', 'slug': 'gaming-juegos-ps', 'icon': '🎮', 'description': 'Discos y códigos para PS4 y PS5.', 'order': 50},
            {'name': 'Juegos para Xbox', 'slug': 'gaming-juegos-xbox', 'icon': '❎', 'description': 'Juegos para consolas Xbox.', 'order': 60},
            {'name': 'Juegos para Nintendo', 'slug': 'gaming-juegos-nintendo', 'icon': '🍄', 'description': 'Juegos para Nintendo Switch y anteriores.', 'order': 70},
            {'name': 'Juegos de PC', 'slug': 'gaming-juegos-pc', 'icon': '💻', 'description': 'Códigos de Steam y juegos físicos PC.', 'order': 80},
            {'name': 'Mandos y Controles', 'slug': 'gaming-mandos', 'icon': '🕹️', 'description': 'Joysticks, controles y mandos arcade.', 'order': 90},
            {'name': 'Sillas Gaming y Escritorios', 'slug': 'gaming-sillas', 'icon': '💺', 'description': 'Mobiliario para gamers.', 'order': 100},
            {'name': 'Volantes y Simuladores', 'slug': 'gaming-volantes', 'icon': '🏎️', 'description': 'Volantes, pedales y simuladores de vuelo.', 'order': 110},
            {'name': 'Realidad Virtual (VR)', 'slug': 'gaming-vr', 'icon': '🥽', 'description': 'Gafas VR y accesorios.', 'order': 120},
            {'name': 'Cuentas y Monedas Virtuales', 'slug': 'gaming-cuentas', 'icon': '🪙', 'description': 'Puntos, skins y cuentas.', 'order': 130},
            {'name': 'Coleccionables Gaming', 'slug': 'gaming-coleccionables', 'icon': '👾', 'description': 'Figuras, amiibos y merchandising.', 'order': 140},
        ]
    }

    for cat_slug, subs in subcategories_data.items():
        try:
            category = Category.objects.get(slug=cat_slug)
            for sub in subs:
                Subcategory.objects.update_or_create(
                    slug=sub['slug'],
                    defaults={
                        'category': category,
                        'name': sub['name'],
                        'icon': sub['icon'],
                        'description': sub['description'],
                        'keywords': sub['name'].lower(),
                        'order': sub['order'],
                    }
                )
        except Category.DoesNotExist:
            continue

def remove_tech_gaming(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_more_pet_accessories'),
    ]

    operations = [
        migrations.RunPython(expand_tech_gaming, remove_tech_gaming),
    ]
