# Generated by Django 6.0.5 on 2026-08-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expo Push Token'),
        ),
    ]
