# Generated by Django 6.0.5 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_profile_pro_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
