# Generated by Django 6.0.5 on 2026-08-17 16:00

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    """Fase 1 del nuevo motor de búsqueda (applications/core/search.py):
    activa las extensiones de PostgreSQL 'unaccent' y 'pg_trgm', y crea el
    índice GIN trigram sobre Listing.title que necesita el fallback fuzzy.
    No conecta nada a Web/App todavía.
    """

    dependencies = [
        ('core', '0058_fix_site_domain_igualo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='listing_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
