# Generated by Django 6.0.4 on 2026-08-17 19:03
# Editado: AddField address_text antes de RemoveField location + copy de datos,
# + seed de geografía (17 departamentos / 153 municipios) + backfill de status/geocodificación.

import unicodedata

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def copy_location_to_address_text(apps, schema_editor):
    Listing = apps.get_model("core", "Listing")
    Listing.objects.all().update(address_text=F("location"))


def seed_geo(apps, schema_editor):
    from django.utils.text import slugify
    from applications.core.geo_data import DEPARTMENTS

    Department = apps.get_model("core", "Department")
    City = apps.get_model("core", "City")

    for item in DEPARTMENTS:
        dept, created = Department.objects.get_or_create(
            slug=item["slug"], defaults={"name": item["name"]}
        )
        if not created and dept.name != item["name"]:
            dept.name = item["name"]
            dept.save(update_fields=["name"])
        for city_name in item["cities"]:
            City.objects.get_or_create(
                slug=slugify(city_name),
                defaults={"name": city_name, "department": dept},
            )


def backfill_listings(apps, schema_editor):
    Listing = apps.get_model("core", "Listing")
    Department = apps.get_model("core", "Department")
    City = apps.get_model("core", "City")

    def norm(value):
        return "".join(
            c for c in unicodedata.normalize("NFD", value or "")
            if unicodedata.category(c) != "Mn"
        ).lower()

    # 1) status desde is_active (los inactivos se mapean a "paused": no se
    #    puede inferir sold/expired de los datos históricos)
    Listing.objects.filter(is_active=True).update(status="active")
    Listing.objects.filter(is_active=False).update(status="paused")

    # 2) geocodificación conservadora del texto de dirección
    cities = list(City.objects.select_related("department").all())
    departments = list(Department.objects.all())

    for listing in Listing.objects.all().iterator():
        text = norm(listing.address_text)
        if not text:
            continue
        city = None
        dept = None
        for c in cities:
            if c.name and norm(c.name) and norm(c.name) in text:
                city = c
                break
        if city:
            dept = city.department
        else:
            for d in departments:
                if d.name and norm(d.name) in text:
                    dept = d
                    break
        if city or dept:
            Listing.objects.filter(pk=listing.pk).update(
                department_id=dept.id if dept else None,
                city_id=city.id if city else None,
            )


class Migration(migrations.Migration):

    # No atómica: el DROP COLUMN de location deja "pending trigger events" en
    # Postgres y bloquea el CREATE INDEX en la misma transacción.
    atomic = False

    dependencies = [
        ('core', '0059_enable_search_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=100, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='address_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='dirección'),
        ),
        migrations.RunPython(copy_location_to_address_text, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Nuevo'), ('used', 'Usado')], max_length=12, null=True, verbose_name='condición'),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('sold', 'Vendido'), ('expired', 'Expirado')], default='active', max_length=10, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)], verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, help_text='¿Está el anuncio visible al público? (sincronizado desde status)', verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.brand', verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.city', verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.department', verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='listing',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.department', verbose_name='departamento'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.brand', verbose_name='marca')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='core.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='core.model', verbose_name='modelo'),
        ),
        migrations.RunPython(seed_geo, migrations.RunPython.noop),
        migrations.RunPython(backfill_listings, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['created_at'], name='listing_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'category', 'created_at'], name='listing_status_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'city', 'category', 'created_at'], name='listing_status_city_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'brand', 'created_at'], name='listing_status_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'model', 'created_at'], name='listing_status_model_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'city', 'model', 'created_at'], name='listing_status_city_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'paused', 'sold', 'expired'])), name='listing_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('condition__isnull', True), ('condition__in', ['new', 'used']), _connector='OR'), name='listing_condition_valid'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('year__isnull', True), models.Q(('year__gte', 1950), ('year__lte', 2100)), _connector='OR'), name='listing_year_range'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('brand', 'name'), ('brand', 'slug')},
        ),
    ]