# Generated by Django 6.0.4 on 2026-08-17 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_geo_brand_model_listing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'department', 'created_at'], name='listing_status_dept_idx'),
        ),
    ]
