# Generated by Django 6.0.5 on 2026-08-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_empleo_subcategories_por_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Enciende o apaga el aviso de mejoras en el panel de administración.', verbose_name='Alerta activa')),
                ('title', models.CharField(default='Estamos mejorando Igualo ✨', max_length=120, verbose_name='Título del aviso')),
                ('message', models.TextField(default='La plataforma está recibiendo nuevas funciones y ajustes en estos momentos. Si notas algo distinto o algún comportamiento raro, es parte de las mejoras — todo sigue funcionando con normalidad.', verbose_name='Mensaje')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
            ],
            options={
                'verbose_name': 'Alerta del sistema',
                'verbose_name_plural': 'Alertas del sistema',
            },
        ),
    ]
